### ISSUE TITLE
Error loading stashed private vars

### ISSUE THREAD

**Issue by john-shaffer** [tonsky/clj-reload#1]
Having a private that is loaded from stash, such as

```
(defonce ^:private abc {})
```

results in

```
; Execution error (IllegalStateException) at clj-reload.util/ns-load-file (util.clj:93).
; var: clj-reload.stash/abc is not public
```

This seems to happen because the ^:private metadata is retained when the var is stashed.

**Comment by tonsky** [comment]
Thanks! Pushed 0.1.1
