### ISSUE TITLE
Large codebase that fails with clj-reload but not tools namespace.

### ISSUE THREAD

**Issue by jasonjckn** [tonsky/clj-reload#12]
Hey I have large codebase at 'megacorp', that I can't share, but it failing to be loaded on initial start-up via clj-reload, but works fine with tools namespace, do you have any tips on what to post here to help you diagnose the issue, i haven't had much time to dive into it, i'll take a longer look at the weekend, but it looks like it could be an issue with clj-reload. i'm getting errors like 'foo' alias does not exist when its clearly required. I can't share code, or filenames, but I can anonymize the data if you tell me what to send.

**Comment by tonsky** [comment]
Do you mean it just takes too long to load? Or there are exceptions?

**Comment by tonsky** [comment]
> i'm getting errors like 'foo' alias does not exist when its clearly required

I would love to hear more about this, maybe the minimal example. Could be the case that we look into the files we shouldn’t be looking

**Comment by jasonjckn** [comment]
> Do you mean it just takes too long to load? Or there are exceptions?

yes exceptions surrounding using a namespace alias that should have been required (and was). 

i'm hoping to have time this weekend to investigate, thanks.

**Comment by jasonjckn** [comment]
I spent more time looking at this on the weekend, and I can only reproduce on one of my computers, with a specific build of emacs v30. So i'm just going to write this off some kind of corrupted file and/or buggy emacs. It's not really worth my time to try and narrow down the problem beyond that.  Thanks for entertaining me this briefly, and your work in general is quite nice, gonna close this issue, cheers.

P.S. That's wild you also created the popular Fira Code, ontop of your popular clojure stuff, just learned that now. I'm a bit of an amateurish font designer, created https://github.com/jasonjckn/tensora-mono-font, its not very good, i have very little graphic design experience, but anyways you might find it interesting/unique.
