### ISSUE TITLE
Is there a way for a kept thing to see reloaded vars?

### ISSUE THREAD

**Issue by nzsp-lg** [tonsky/clj-reload#15]
I use `defonce` to keep a system running when a namespace is reloaded. In this example the system is another thread but my actual code is using a web server.

If I reload a namespace with clj-reload, it seems that the code in the 'kept' system can't see the changed values of the vars in that namespace.

```clj
(ns main)

(defn example-fn [] :first-version)

(defonce system
  (future
    (loop []
      (println "------------" ((var example-fn)))
      (Thread/sleep 2000)
      (recur))))
```

In the example below I run a repl and require the `main` namespace which starts the system printing the result of calling `example-fn` every couple of seconds.

```sh
> clj -Sdeps '{:deps {io.github.tonsky/clj-reload {:mvn/version "LATEST"}}}'
Clojure 1.12.0
user=> (require '[clj-reload.core :as r])
nil
user=> (r/init {})
{:since 1729206241728, ...} 
user=> (require 'main)
nil
------------ :first-version
------------ :first-version
------------ :first-version
------------ :first-version
```

Then I edit `main.clj` to change `example-fn` to `(defn example-fn [] :second-version)`. And reload in the repl, but the system carries on printing the first version.

```sh
user=> (r/reload)
Unloading main
Loading main
{:unloaded [main], :loaded [main]}
------------ :first-version
------------ :first-version
------------ :first-version
------------ :first-version
user=> (main/example-fn)
:second-version
------------ :first-version
------------ :first-version
```

Is there any way to reload the namespace and have the 'system' see the changes to the vars in the reloaded namespace. I thought that using `var` or the reader tag `#'` might fix this.

**Comment by nzsp-lg** [comment]
Just found `ns-resolve` and using that to get the value of the var does work. eg.

```clj
(println "------------" ((ns-resolve 'main 'example-fn)))
```

For my use case I can work with that, I want to keep a web server running while using reload to update routes and middleware and I can have one `ns-resolve` to get the top level handler.

Feel free to close this, but perhaps this is worth a warning in the docs. I guess my understanding of using `var` is incomplete.

**Comment by tonsky** [comment]
Thanks! Updated README
