### ISSUE TITLE
Fails to parse files with aliased keywords

### ISSUE THREAD

**Issue by leafgarland** [tonsky/clj-reload#2]
```clj
  (require '[clj-reload.parse])

  (defn read-str [s]
    (clj-reload.parse/read-file (java.io.PushbackReader. (java.io.StringReader. s)) nil))

  (read-str "(ns broken (:require [clojure.string :as string])) ::string/foo")
  ; (err) Execution error at clj-reload.parse/read-file$fn (parse.clj:79).
  ; (err) Invalid token: ::string/foo
```

When given a namespace that uses an aliased keyword `read-file` throws an exception `"Invalid token: ::string/foo"`.

I can see that this uses `clojure.core/read` (with `*read-eval*` set to false) which is where the exception comes from. `clojure.core/read` will use `*ns*` and the aliases of the current namespace to resolve the aliased keyword. But as the file is read with `*read-eval*` set to false the namespace form is not evaluated and no aliases are created, so the keyword cannot be resolved.

I'm not sure how to fix this without using another reader (like clojure.tools.reader). It could work by creating namespaces and adding aliases into them.

```clj
  (binding [*read-eval* false
            *ns* (create-ns 'hacky)]
    (alias 'string 'clojure.string)
    (read (java.io.PushbackReader. (java.io.StringReader. "::string/foo"))))
```

But this obviously has an impact on the current environment which might not be ideal.

**Comment by tonsky** [comment]
Looks like there’s a way through `*reader-resolver*`. Published 0.1.2
