### ISSUE TITLE
minor issue with faux cyclic dependency

### ISSUE THREAD

**Issue by joinr** [tonsky/clj-reload#6]
Had some legacy code whereby

```clojure
(ns blah 
   (:require [foo bar blah]))  ;;accidental self-reference
```

clojure compiler is smart enough to silently ignore this and not load self-references in the ns form; e.g. no cycle is detected when using legacy reload-all behavior or any loading.  clj-reload sees the form and (rightly, or wrongly depending preferred semantics) claims there's an effective cycle in the dependency.  I opted to side with clj-reload and prune the cycle, posting issue for reference.

**Comment by tonsky** [comment]
Thanks! I fixed it
