### ISSUE TITLE
Loading namespaces with edn record constructors fails

### ISSUE THREAD

**Issue by joinr** [tonsky/clj-reload#7]
java.lang.RuntimeException: Record construction syntax can only be used when *read-eval* == true

clj-reload provides no apparent way to override [the default binding here](https://github.com/tonsky/clj-reload/blob/main/src/clj_reload/util.clj#L34).  clojure.core/require reload-all works out of the box in these situations.

**Comment by tonsky** [comment]
Thanks! Should be fixed
