### ISSUE TITLE
Lock

### ISSUE THREAD

**Issue by vemv** [tonsky/clj-reload#9]
Parallel code reloading isn't safe.

So it would seem a good idea to add a lock so that one cannot reload concurrently?

This is a plausible scenario when using clj-reload via CIDER.

We could add a lock ourselves (as we do with t.n), but having it here would seem best.

WDYT?

Cheers - V

**Comment by tonsky** [comment]
Sure. Pushed 0.6.0

**Comment by vemv** [comment]
Thanks! We're updating cider-nrepl with it soon.
